-- INSERT INTO Student (id, name,average) VALUES (1,'Mario',9.7)
-- INSERT INTO Student (id, name,average) VALUES (2,'Mario2',7.3)
-- INSERT INTO Student (id, name,average) VALUES (3,'Mario3',8.6)
-- INSERT INTO Student (id, name,average) VALUES (11,'Mario',5.7)
-- INSERT INTO Student (id, name,average) VALUES (22,'Mario21',7.8)
-- INSERT INTO Student (id, name,average) VALUES (33,'Mario32',8.7)
--
-- INSERT INTO Lesson (id, lecturer ) VALUES (1,'prof Mario_1')
-- INSERT INTO Lesson (id, lecturer ) VALUES (2,'prof Mario_2')
-- INSERT INTO Lesson (id, lecturer ) VALUES (3,'prof Mario_3')
-- INSERT INTO Lesson (id, lecturer ) VALUES (4,'prof Mario_4')
--
